#!/bin/bash
echo "Running git pre-commit hook: ktlintFormat"
./gradlew ktlintFormat
ktlintCheckStatus=$?
# return 1 if check fails
if [[ $ktlintCheckStatus -ne 0 ]]; then
     exit 1
else
     exit 0
fi