name: Android CI

on:
  push:
    branches: [ main, dev ]
  pull_request: 
    branches: [ main, dev, 'release/**' ] 

jobs: 
  Unit-Test:
    runs-on: ubuntu-latest
   
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: |
          ./gradlew test

      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "app/build/test-results/testDebugUnitTest/TEST-*.xml"